### ISSUE TITLE
Download link for manual install is broken

### ISSUE THREAD

**Issue by mbreslein-thd** [RocketChat/docs#10]
Hi,
The Links in the guides for manually installing rocket.chat return a 404 instead of the latest build:
https://docs.rocket.chat/deploy/prepare-for-your-deployment/other-deployment-methods/manual-installation/debian-based-distros/debian

As a workaround I got the latest build from the CDN to get my install back up and running:
https://cdn-download.rocket.chat/build/rocket.chat-6.1.2.tgz

**Comment by zmijunkie** [comment]
Downloading the latest version from https://releases.rocket.chat/latest/download worked for three years and now it is broken. It has been an easy way to obtain this software. Hopefully this gets fixed soon.

**Comment by Rodriq** [comment]
@mbreslein-thd Please can you point to the exact position in the docs?
https://releases.rocket.chat/latest/download  seems to be working. Can you verify?

**Comment by zmijunkie** [comment]
Thanks works for me !

**Comment by mbreslein-thd** [comment]
It didn't work when I opened the issue. Seems to be fine now.

**Comment by eXtrem0us** [comment]
Hey Guys, https://releases.rocket.chat/latest/download is broken again.
