### ISSUE TITLE
4.8.7 still supported?

### ISSUE THREAD

**Issue by abelbabel** [RocketChat/docs#11]
Hi,

is 4.8.7 still supported? It is not listed in

https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions

but is - as far as I got it right - currently the last version of the 4.8 branch. Am I right that if it was the forever last version of the 4.8 branch it has to be supported 6 months from release date, that is May 24th.

Regards
abelbabel

**Comment by marceloschmidt** [comment]
Hey @abelbabel you're right, I see that the version there hasn't been updated lately. Thanks for the heads up, I will make sure it's updated this week.
