### ISSUE TITLE
Broken link for Integration Documentation

### ISSUE THREAD

**Issue by vcidst** [RocketChat/docs#2]
Hey folks, Our documentation of [Rasa RocketChat connector](https://rasa.com/docs/rasa/connectors/rocketchat/) links to the RocketChat Integrations documentation. It seems like this link is now broken, https://docs.rocket.chat/guides/administration/admin-panel/integrations

Can you tell us what should I replace this documentation link with?

**Comment by Rodriq** [comment]
This needs to be updated from the Rasa.com's end. 
Here is the correct link it is supposed to point to https://docs.rocket.chat/use-rocket.chat/workspace-administration/integrations

We've created a redirect, so it should point to the docs normally.
Thank you @vcidst
