### ISSUE TITLE
Placeholder or syntax used in this documentation system ?

### ISSUE THREAD

**Issue by aadarsh-nagrath** [RocketChat/docs#37]
Below the Key references section why the rest of the doc is formatted with this - 
{% content-ref url="..." %} and [...](...) ?
![image](https://github.com/RocketChat/docs/assets/92307537/99d7a22e-85ee-4fd1-ba24-2ced38131341)

The formatting you've provided, such as {% content-ref url="..." %} and [...](...), appears to be a placeholder or syntax used in a particular documentation system or platform to reference or link to other documents or resources. It's not meant to be presented as part of the final documentation that end-users will read.

In the final documentation, this formatting should be replaced with the actual content or links that it points to. Users should see a clear and direct link or description of the resource they can access, rather than the placeholder or reference code.

Here's how it might look in the final documentation:

Minimum Requirements
Minimum Requirements for Client Apps

Support
Rocket.Chat Support Structure

Developer Guides
Developer Portal

In this way, users can easily access the relevant information without seeing the underlying formatting or placeholders.

**Comment by Roxie-32** [comment]
Hi @aadarsh-nagrath 

Thank you for this. We use [Gitbooks](https://www.gitbook.com/) for our documentation and you can find our published documentation here:
- [User Dococumentation](https://docs.rocket.chat/)
- [Developer documentation](https://developer.rocket.chat/)

What you see here is the flavor of markdown Gitbook uses to store our documentation on Github.
