### ISSUE TITLE
Incorrect CLI name mongo in manual install document

### ISSUE THREAD

**Issue by preeder** [RocketChat/docs#4]
In deploy/prepare-for-your-deployment/other-deployment-methods/manual-installation/debian-based-distros/ubuntu , there is an instruction to run
`mongo --eval "printjson(rs.initiate())"`
The command name is mongosh, not mongo.

I think it is also similarly wrong for Debian and Kali, but I'm not sure.

**Comment by techwithbhavya** [comment]
Hey, I would like to work on this issue.

**Comment by Rodriq** [comment]
@Roxie-32 Please can we get your findings here?

**Comment by Roxie-32** [comment]
Both mongo and mongosh are command-line interfaces for interacting with MongoDB.  It depends on which one you have installed and are comfortable using. Both works  fine for initializing a replica set in MongoDB. 
Mongosh is however a recent shell :  https://www.mongodb.com/blog/post/introducing-the-new-shell

**Comment by easymoney322** [comment]
Old 'Mongo" shell [is deprecated since 5.0](https://www.mongodb.com/docs/v6.0/reference/mongo/)

> The mongo shell has been deprecated in MongoDB v5.0. The replacement is [mongosh.](https://www.mongodb.com/docs/mongodb-shell/#mongodb-binary-bin.mongosh)
> 
> Older mongo shell documentation is included with the corresponding documentation for that MongoDB release.


And the upcoming MongoDB is 8.0.

Thus, I'd suggest updating commands in docs. 

I will fix commands and open a pull request soon.
