### ISSUE TITLE
Rest API update-user documentation.

### ISSUE THREAD

**Issue by demesg** [RocketChat/docs#56]
Please point out that roles in /api/v1/users.update needs to be the ID of the role not the name. Wellknown roles in rocketchat has the same id as Name. But custom roles has not. 

https://developer.rocket.chat/reference/api/rest-api/endpoints/user-management/users-endpoints/update-user

**Comment by rachana-visavadiya** [comment]
The `Roles` parameter description is now updated for the [Update User](https://developer.rocket.chat/reference/api/rest-api/endpoints/user-management/users-endpoints/update-user) endpoint. Thank you!
