### ISSUE TITLE
Team owners/managers

### ISSUE THREAD

**Issue by ArthurJahn** [RocketChat/docs#7]
Reading the docs, it doesn't get clear if a team can have a member with permissions to manage that team specifically and not the entire workspace. How does that work?

**Comment by Rodriq** [comment]
@ArthurJahn On all Rocket.Chat [Rooms](https://docs.rocket.chat/use-rocket.chat/user-guides/rooms), you can assign a user [permissions](https://docs.rocket.chat/use-rocket.chat/workspace-administration/permissions) to control the said room.

See https://docs.rocket.chat/setup-and-configure/roles-in-rocket.chat

![image](https://user-images.githubusercontent.com/39289592/227920508-01887ddd-5527-4b0b-9827-8f47829f2b70.png)

**Comment by ArthurJahn** [comment]
Great! Thanks
