### ISSUE TITLE
Snap deployment: error: cannot find app "initcaddy" in "rocketchat-server"

### ISSUE THREAD

**Issue by mdPlusPlus** [RocketChat/docs#79]
I'm following this guide: https://github.com/RocketChat/docs/blob/main/deploy/deploy-rocket.chat/deploy-with-snaps.md#auto-ssl-with-snaps

At one point, there is this snippet:
```
sudo snap set rocketchat-server caddy-url=https://<your-domain-name>
sudo snap set rocketchat-server caddy=enable
sudo snap set rocketchat-server https=enable
sudo snap run rocketchat-server.initcaddy
```

But `sudo snap run rocketchat-server.initcaddy` results in the error:  
`error: cannot find app "initcaddy" in "rocketchat-server"`

Is the documentation outdated? I'm running rocketchat-server 6.5.2 via snap.

**Comment by Neowarex** [comment]
That is to set up Auto SSL with Snaps for older snaps, no longer needed it seems?

**Comment by Roxie-32** [comment]
Hi, 
Thank you for pointing this out. Those steps were for users with older Snaps versions, and they are now obsolete, so they have been removed. 

Kindly follow the current steps in the[ documentation](https://docs.rocket.chat/deploy/deploy-rocket.chat/deploy-with-snaps#auto-ssl-with-snaps) .
