### ISSUE TITLE
hint

### ISSUE THREAD

**Issue by UmaRajamani** [RocketChat/docs#89]
% hint style="info" %} As of December 15, 2023, Rocket.Chat has ceased support for connections from cloud services and official mobile/desktop apps to workspaces running legacy versions outside our support window. Users on unsupported legacy servers are advised to upgrade to the latest Rocket.Chat version to ensure continued access to cloud, mobile, and desktop applications. Each Rocket.Chat version is supported for six months post-release. {% endhint %}

**Comment by Faria1212** [comment]
What is the issue here?
