### ISSUE TITLE
AWS deployment CERTBOT cert only

### ISSUE THREAD

**Issue by shawshankkumar** [RocketChat/docs#9]
https://docs.rocket.chat/deploy/prepare-for-your-deployment/cloud-deployments/aws

in this tutorial, we are only getting a certificate from CERTBOT, not the entire setup. In my personal experience, we could setup nginx first, then use certbot to get a certificate and configure it and then restart nginx. This makes sure that there is less things for the user to configure (and less errors).

I would be curious to know why isn't this the case, maybe I don't know something.

**Comment by Rodriq** [comment]
@shawshankkumar Do you think you'll be able to open a PR about this?

**Comment by shawshankkumar** [comment]
Sure thing. I'll try my best!

**Comment by Roxie-32** [comment]
Closing this because we now have an improved recommended way for [enabling HTTPS for Docker deployments](https://docs.rocket.chat/deploy/deploy-rocket.chat/deploy-with-docker-and-docker-compose#enable-https).
